In [1]:
# not recommended for live trading?
import pandas as pd
import yfinance as yf

In [ ]:
# https://ranaroussi.github.io/yfinance/reference/index.html

In [2]:
# ticker = stock name for company

company = yf.Tickers("MSFT")
data = company.history()
print(data.columns)

[*********************100%***********************]  1 of 1 completed

MultiIndex([(       'Close', 'MSFT'),
            (   'Dividends', 'MSFT'),
            (        'High', 'MSFT'),
            (         'Low', 'MSFT'),
            (        'Open', 'MSFT'),
            ('Stock Splits', 'MSFT'),
            (      'Volume', 'MSFT')],
           names=['Price', 'Ticker'])

In [3]:
data.head()

Price,Close,Dividends,High,Low,Open,Stock Splits,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,
2025-06-02,461.970001,0.0,462.109985,456.890015,457.140015,0.0,16626500
2025-06-03,462.970001,0.0,464.140015,460.859985,461.470001,0.0,15743800
2025-06-04,463.869995,0.0,465.690002,463.019989,464.000000,0.0,14162700
2025-06-05,467.679993,0.0,469.649994,464.029999,464.959991,0.0,20131700
2025-06-06,470.380005,0.0,473.339996,468.779999,470.089996,0.0,15285600

In [5]:
yf.Lookup("MSFT").all

,exchange,industryLink,industryName,quoteType,rank,regularMarketChange,regularMarketPercentChange,regularMarketPrice,shortName
symbol,,,,,,,,,
MSFT,NMS,https://finance.yahoo.com/sector/technology,Technology,equity,27616,-1.944977,-0.395280,490.105011,Microsoft Corporation
MSFT.MX,MEX,https://finance.yahoo.com/sector/technology,Technology,equity,20082,-28.769531,-0.311687,9201.500000,MICROSOFT CORP
MSFU,NGM,NaN,NaN,etf,20022,-0.430000,-0.883502,48.220001,Direxion Daily MSFT Bull 2X Sha
MSFD,NGM,NaN,NaN,etf,20013,0.059900,0.526827,11.429900,Direxion Daily MSFT Bear 1X Sha
MSFO,PCX,NaN,NaN,etf,20006,-0.100401,-0.567237,17.599600,Tidal ETF Trust II YieldMax MSF
MSFT34.SA,SAO,https://finance.yahoo.com/sector/technology,Technology,equity,20006,-1.110001,-0.992046,110.779999,MICROSOFT DRN
MSFT.NE,NEO,https://finance.yahoo.com/sector/technology,Technology,equity,20006,-0.590000,-1.642997,35.320000,MICROSOFT CDR (CAD HEDGED)
O3CN.Z,ZRH,NaN,NaN,index,20002,1.690002,1.207403,141.729996,iSTX.Inve.Leveraged -3X MSFT I
^MSFD-NV,ASE,NaN,NaN,index,20002,0.123200,1.094638,11.378100,DIREXION DAILY MSFT BEAR 1X SHA
MSFT.BA,BUE,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-25.000000,-0.123305,20225.000000,MICROSOFT CORP CEDEAR EACH 30 R
MSFT.L,LSE,NaN,NaN,etf,20001,2.500000,0.340832,736.000000,LEVERAGE SHARES PUBLIC LIMITED
3SMF.L,LSE,NaN,NaN,etf,20001,0.549999,1.494563,37.349998,LEVERAGE SHARES PUBLIC LIMITED
MSFY.NE,NEO,NaN,NaN,etf,20001,-0.400000,-1.739129,22.600000,MICROSOFT (MSFT) YIELD SHARES P
MSFL,NGM,NaN,NaN,etf,20001,-0.260099,-0.882291,29.219900,GraniteShares 2x Long MSFT Dail
^MSFU-EU,ASE,NaN,NaN,index,20001,-21444.562500,-2.155806,973290.750000,DIREXION DAILY MSFT BULL 1.5X S
^MSFD-TC,ASE,NaN,NaN,index,20001,3080.968750,1.094976,284454.093750,DIREXION DAILY MSFT BEAR 1X SHA
^MSFO-NV,ASE,NaN,NaN,index,20001,-0.141300,-0.792766,17.682400,YIELDMAX MSFT OPTION INCOME STR
46JL.Z,ZRH,NaN,NaN,index,20001,-933.265625,-1.162921,79280.687500,iSTOXX Leveraged 3X MSFT I
MSFT.SN,SGO,https://finance.yahoo.com/sector/technology,Technology,equity,20001,5.970001,1.215688,497.049988,MICROSOFT CORP
MSFT.VI,VIE,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-1.000000,-0.238863,417.649994,MICROSOFT CORP
MSFT.TO,TOR,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-0.560001,-1.560762,35.320000,MICROSOFT CDR (CAD HEDGED)
MSFTCL.SN,SGO,NaN,NaN,equity,20001,-9100.000000,-1.956989,455900.000000,MICROSOFT CORP
^MSFU-TC,ASE,NaN,NaN,index,20001,-24894.250000,-2.501349,970338.500000,DIREXION DAILY MSFT BULL 1.5X S
^MSFU-IV,ASE,NaN,NaN,index,20001,-0.404701,-0.831888,48.249699,DIREXION DAILY MSFT BULL 1.5X S
EVK.DU,DUS,https://finance.yahoo.com/sector/basic_materials,Basic Materials,equity,20001,-0.140001,-0.799094,17.379999,Evonik Industries AG N

In [6]:
yf.Lookup("MSFT").stock

,exchange,industryLink,industryName,quoteType,rank,regularMarketChange,regularMarketPercentChange,regularMarketPrice,shortName
symbol,,,,,,,,,
MSFT,NMS,https://finance.yahoo.com/sector/technology,Technology,equity,27616.0,-1.924988,-0.391218,490.125000,Microsoft Corporation
MSFT.MX,MEX,https://finance.yahoo.com/sector/technology,Technology,equity,20082.0,-28.769531,-0.311687,9201.500000,MICROSOFT CORP
MSFT34.SA,SAO,https://finance.yahoo.com/sector/technology,Technology,equity,20006.0,-1.120003,-1.000896,110.769997,MICROSOFT DRN
MSFT.NE,NEO,https://finance.yahoo.com/sector/technology,Technology,equity,20006.0,-0.579998,-1.615593,35.330002,MICROSOFT CDR (CAD HEDGED)
MSFT.BA,BUE,https://finance.yahoo.com/sector/technology,Technology,equity,20001.0,-25.000000,-0.123457,20225.000000,MICROSOFT CORP CEDEAR EACH 30 R
MSFT.SN,SGO,https://finance.yahoo.com/sector/technology,Technology,equity,20001.0,5.970001,1.215688,497.049988,MICROSOFT CORP
MSFT.VI,VIE,https://finance.yahoo.com/sector/technology,Technology,equity,20001.0,-1.000000,-0.238863,417.649994,MICROSOFT CORP
MSFT.TO,TOR,https://finance.yahoo.com/sector/technology,Technology,equity,20001.0,-0.560001,-1.560762,35.320000,MICROSOFT CDR (CAD HEDGED)
MSFTCL.SN,SGO,NaN,NaN,equity,20001.0,-9100.000000,-1.956989,455900.000000,MICROSOFT CORP
EVK.DU,DUS,https://finance.yahoo.com/sector/basic_materials,Basic Materials,equity,20001.0,-0.140001,-0.799094,17.379999,Evonik Industries AG N
MSFT.AS,AMS,NaN,NaN,equity,20001.0,-0.036900,-0.432297,8.498800,LS 1x Microsoft Tracker ETP
MSFTD.BA,BUE,NaN,NaN,equity,20001.0,-0.100000,-0.606063,16.400000,MICROSOFT CORP CEDEAR EACH 30 R
P47962.MI,MIL,NaN,NaN,equity,20001.0,-0.519999,-2.349745,21.610001,"BPA TB LG MSFT 178,9 B178,9 OP"
10557.HK,HKG,NaN,NaN,equity,NaN,-0.005000,-1.666675,0.295000,NaN
MSFT01.BK,SET,https://finance.yahoo.com/sector/technology,Technology,equity,NaN,-0.060000,-1.260513,4.700000,MSFT01_DR MSFT#BLS
MSFTC.BA,BUE,NaN,NaN,equity,NaN,-0.049999,-0.303026,16.450001,MICROSOFT CORP CEDEAR EACH 30 R
YMSF.DE,GER,NaN,NaN,equity,NaN,-0.022500,-0.255886,8.770500,Leverage Shares PLC E
MSFT80.BK,SET,https://finance.yahoo.com/sector/technology,Technology,equity,NaN,-0.100000,-1.242241,7.950000,MSFT80_DR MSFT#KTB
MSFT06.BK,SET,NaN,NaN,equity,NaN,-0.040000,-0.990098,4.000000,MSFT06_DR MSFT#KKPS
MSFT.WA,WSE,https://finance.yahoo.com/sector/technology,Technology,equity,NaN,0.000000,0.000000,1806.199951,MICROSOFT

In [12]:
yf.Lookup("MSFT").index

,exchange,quoteType,rank,regularMarketChange,regularMarketPercentChange,regularMarketPrice,shortName
symbol,,,,,,,
O3CN.Z,ZRH,index,20002,1.830002,1.307238,141.869995,iSTX.Inve.Leveraged -3X MSFT I
^MSFD-NV,ASE,index,20002,0.123200,1.094638,11.378100,DIREXION DAILY MSFT BEAR 1X SHA
^MSFD-TC,ASE,index,20001,3080.968750,1.094976,284454.093750,DIREXION DAILY MSFT BEAR 1X SHA
^MSFU-EU,ASE,index,20001,-21444.562500,-2.155806,973290.750000,DIREXION DAILY MSFT BULL 1.5X S
^MSFO-NV,ASE,index,20001,-0.141300,-0.792766,17.682400,YIELDMAX MSFT OPTION INCOME STR
46JL.Z,ZRH,index,20001,-1013.796875,-1.263418,79200.156250,iSTOXX Leveraged 3X MSFT I
^MSFU-TC,ASE,index,20001,-24894.250000,-2.501349,970338.500000,DIREXION DAILY MSFT BULL 1.5X S
^MSFU-IV,ASE,index,20001,-0.401699,-0.825785,48.252701,DIREXION DAILY MSFT BULL 1.5X S
^MSFO-TC,ASE,index,20001,-3571.757812,-5.823678,57759.890625,YIELDMAX MSFT OPTION INCOME STR
^MSFU-NV,ASE,index,20001,-1.083099,-2.177627,48.654499,DIREXION DAILY MSFT BULL 1.5X S
^NY2LMSFT,NYS,index,20001,-11.351929,-0.816958,1378.127075,ICE Leveraged 2x MSFT Index
^MSFD-EU,ASE,index,20001,3080.968750,1.094976,284454.093750,DIREXION DAILY MSFT BEAR 1X SHA
^MSFO-EU,ASE,index,20001,73.239746,1.387973,5349.979980,YIELDMAX MSFT OPTION INCOME STR
^MSFD-IV,ASE,index,20001,0.047199,0.414774,11.425300,DIREXION DAILY MSFT BEAR 1X SHA
46J7.Z,ZRH,index,20001,0.250000,0.434103,57.840000,iSTOXX Inv.Leveraged -1X MSFT I