In [1]:
# not recommended for live trading?
import pandas as pd
import yfinance as yf

In [ ]:
# https://ranaroussi.github.io/yfinance/reference/index.html

In [6]:
# ticker = stock name for company

company = yf.Ticker("MSFT")
data = company.history()
print(data.columns)

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'], dtype='object')

In [3]:
data.head()

Price,Close,Dividends,High,Low,Open,Stock Splits,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,
2025-06-02,461.970001,0.0,462.109985,456.890015,457.140015,0.0,16626500
2025-06-03,462.970001,0.0,464.140015,460.859985,461.470001,0.0,15743800
2025-06-04,463.869995,0.0,465.690002,463.019989,464.000000,0.0,14162700
2025-06-05,467.679993,0.0,469.649994,464.029999,464.959991,0.0,20131700
2025-06-06,470.380005,0.0,473.339996,468.779999,470.089996,0.0,15285600

In [5]:
yf.Lookup("MSFT").all

,exchange,industryLink,industryName,quoteType,rank,regularMarketChange,regularMarketPercentChange,regularMarketPrice,shortName
symbol,,,,,,,,,
MSFT,NMS,https://finance.yahoo.com/sector/technology,Technology,equity,27616,-1.944977,-0.395280,490.105011,Microsoft Corporation
MSFT.MX,MEX,https://finance.yahoo.com/sector/technology,Technology,equity,20082,-28.769531,-0.311687,9201.500000,MICROSOFT CORP
MSFU,NGM,NaN,NaN,etf,20022,-0.430000,-0.883502,48.220001,Direxion Daily MSFT Bull 2X Sha
MSFD,NGM,NaN,NaN,etf,20013,0.059900,0.526827,11.429900,Direxion Daily MSFT Bear 1X Sha
MSFO,PCX,NaN,NaN,etf,20006,-0.100401,-0.567237,17.599600,Tidal ETF Trust II YieldMax MSF
MSFT34.SA,SAO,https://finance.yahoo.com/sector/technology,Technology,equity,20006,-1.110001,-0.992046,110.779999,MICROSOFT DRN
MSFT.NE,NEO,https://finance.yahoo.com/sector/technology,Technology,equity,20006,-0.590000,-1.642997,35.320000,MICROSOFT CDR (CAD HEDGED)
O3CN.Z,ZRH,NaN,NaN,index,20002,1.690002,1.207403,141.729996,iSTX.Inve.Leveraged -3X MSFT I
^MSFD-NV,ASE,NaN,NaN,index,20002,0.123200,1.094638,11.378100,DIREXION DAILY MSFT BEAR 1X SHA
MSFT.BA,BUE,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-25.000000,-0.123305,20225.000000,MICROSOFT CORP CEDEAR EACH 30 R
MSFT.L,LSE,NaN,NaN,etf,20001,2.500000,0.340832,736.000000,LEVERAGE SHARES PUBLIC LIMITED
3SMF.L,LSE,NaN,NaN,etf,20001,0.549999,1.494563,37.349998,LEVERAGE SHARES PUBLIC LIMITED
MSFY.NE,NEO,NaN,NaN,etf,20001,-0.400000,-1.739129,22.600000,MICROSOFT (MSFT) YIELD SHARES P
MSFL,NGM,NaN,NaN,etf,20001,-0.260099,-0.882291,29.219900,GraniteShares 2x Long MSFT Dail
^MSFU-EU,ASE,NaN,NaN,index,20001,-21444.562500,-2.155806,973290.750000,DIREXION DAILY MSFT BULL 1.5X S
^MSFD-TC,ASE,NaN,NaN,index,20001,3080.968750,1.094976,284454.093750,DIREXION DAILY MSFT BEAR 1X SHA
^MSFO-NV,ASE,NaN,NaN,index,20001,-0.141300,-0.792766,17.682400,YIELDMAX MSFT OPTION INCOME STR
46JL.Z,ZRH,NaN,NaN,index,20001,-933.265625,-1.162921,79280.687500,iSTOXX Leveraged 3X MSFT I
MSFT.SN,SGO,https://finance.yahoo.com/sector/technology,Technology,equity,20001,5.970001,1.215688,497.049988,MICROSOFT CORP
MSFT.VI,VIE,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-1.000000,-0.238863,417.649994,MICROSOFT CORP
MSFT.TO,TOR,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-0.560001,-1.560762,35.320000,MICROSOFT CDR (CAD HEDGED)
MSFTCL.SN,SGO,NaN,NaN,equity,20001,-9100.000000,-1.956989,455900.000000,MICROSOFT CORP
^MSFU-TC,ASE,NaN,NaN,index,20001,-24894.250000,-2.501349,970338.500000,DIREXION DAILY MSFT BULL 1.5X S
^MSFU-IV,ASE,NaN,NaN,index,20001,-0.404701,-0.831888,48.249699,DIREXION DAILY MSFT BULL 1.5X S
EVK.DU,DUS,https://finance.yahoo.com/sector/basic_materials,Basic Materials,equity,20001,-0.140001,-0.799094,17.379999,Evonik Industries AG N

In [6]:
yf.Lookup("MSFT").stock

,exchange,industryLink,industryName,quoteType,rank,regularMarketChange,regularMarketPercentChange,regularMarketPrice,shortName
symbol,,,,,,,,,
MSFT,NMS,https://finance.yahoo.com/sector/technology,Technology,equity,27616.0,-1.924988,-0.391218,490.125000,Microsoft Corporation
MSFT.MX,MEX,https://finance.yahoo.com/sector/technology,Technology,equity,20082.0,-28.769531,-0.311687,9201.500000,MICROSOFT CORP
MSFT34.SA,SAO,https://finance.yahoo.com/sector/technology,Technology,equity,20006.0,-1.120003,-1.000896,110.769997,MICROSOFT DRN
MSFT.NE,NEO,https://finance.yahoo.com/sector/technology,Technology,equity,20006.0,-0.579998,-1.615593,35.330002,MICROSOFT CDR (CAD HEDGED)
MSFT.BA,BUE,https://finance.yahoo.com/sector/technology,Technology,equity,20001.0,-25.000000,-0.123457,20225.000000,MICROSOFT CORP CEDEAR EACH 30 R
MSFT.SN,SGO,https://finance.yahoo.com/sector/technology,Technology,equity,20001.0,5.970001,1.215688,497.049988,MICROSOFT CORP
MSFT.VI,VIE,https://finance.yahoo.com/sector/technology,Technology,equity,20001.0,-1.000000,-0.238863,417.649994,MICROSOFT CORP
MSFT.TO,TOR,https://finance.yahoo.com/sector/technology,Technology,equity,20001.0,-0.560001,-1.560762,35.320000,MICROSOFT CDR (CAD HEDGED)
MSFTCL.SN,SGO,NaN,NaN,equity,20001.0,-9100.000000,-1.956989,455900.000000,MICROSOFT CORP
EVK.DU,DUS,https://finance.yahoo.com/sector/basic_materials,Basic Materials,equity,20001.0,-0.140001,-0.799094,17.379999,Evonik Industries AG N
MSFT.AS,AMS,NaN,NaN,equity,20001.0,-0.036900,-0.432297,8.498800,LS 1x Microsoft Tracker ETP
MSFTD.BA,BUE,NaN,NaN,equity,20001.0,-0.100000,-0.606063,16.400000,MICROSOFT CORP CEDEAR EACH 30 R
P47962.MI,MIL,NaN,NaN,equity,20001.0,-0.519999,-2.349745,21.610001,"BPA TB LG MSFT 178,9 B178,9 OP"
10557.HK,HKG,NaN,NaN,equity,NaN,-0.005000,-1.666675,0.295000,NaN
MSFT01.BK,SET,https://finance.yahoo.com/sector/technology,Technology,equity,NaN,-0.060000,-1.260513,4.700000,MSFT01_DR MSFT#BLS
MSFTC.BA,BUE,NaN,NaN,equity,NaN,-0.049999,-0.303026,16.450001,MICROSOFT CORP CEDEAR EACH 30 R
YMSF.DE,GER,NaN,NaN,equity,NaN,-0.022500,-0.255886,8.770500,Leverage Shares PLC E
MSFT80.BK,SET,https://finance.yahoo.com/sector/technology,Technology,equity,NaN,-0.100000,-1.242241,7.950000,MSFT80_DR MSFT#KTB
MSFT06.BK,SET,NaN,NaN,equity,NaN,-0.040000,-0.990098,4.000000,MSFT06_DR MSFT#KKPS
MSFT.WA,WSE,https://finance.yahoo.com/sector/technology,Technology,equity,NaN,0.000000,0.000000,1806.199951,MICROSOFT

In [12]:
yf.Lookup("MSFT").index

,exchange,quoteType,rank,regularMarketChange,regularMarketPercentChange,regularMarketPrice,shortName
symbol,,,,,,,
O3CN.Z,ZRH,index,20002,1.830002,1.307238,141.869995,iSTX.Inve.Leveraged -3X MSFT I
^MSFD-NV,ASE,index,20002,0.123200,1.094638,11.378100,DIREXION DAILY MSFT BEAR 1X SHA
^MSFD-TC,ASE,index,20001,3080.968750,1.094976,284454.093750,DIREXION DAILY MSFT BEAR 1X SHA
^MSFU-EU,ASE,index,20001,-21444.562500,-2.155806,973290.750000,DIREXION DAILY MSFT BULL 1.5X S
^MSFO-NV,ASE,index,20001,-0.141300,-0.792766,17.682400,YIELDMAX MSFT OPTION INCOME STR
46JL.Z,ZRH,index,20001,-1013.796875,-1.263418,79200.156250,iSTOXX Leveraged 3X MSFT I
^MSFU-TC,ASE,index,20001,-24894.250000,-2.501349,970338.500000,DIREXION DAILY MSFT BULL 1.5X S
^MSFU-IV,ASE,index,20001,-0.401699,-0.825785,48.252701,DIREXION DAILY MSFT BULL 1.5X S
^MSFO-TC,ASE,index,20001,-3571.757812,-5.823678,57759.890625,YIELDMAX MSFT OPTION INCOME STR
^MSFU-NV,ASE,index,20001,-1.083099,-2.177627,48.654499,DIREXION DAILY MSFT BULL 1.5X S
^NY2LMSFT,NYS,index,20001,-11.351929,-0.816958,1378.127075,ICE Leveraged 2x MSFT Index
^MSFD-EU,ASE,index,20001,3080.968750,1.094976,284454.093750,DIREXION DAILY MSFT BEAR 1X SHA
^MSFO-EU,ASE,index,20001,73.239746,1.387973,5349.979980,YIELDMAX MSFT OPTION INCOME STR
^MSFD-IV,ASE,index,20001,0.047199,0.414774,11.425300,DIREXION DAILY MSFT BEAR 1X SHA
46J7.Z,ZRH,index,20001,0.250000,0.434103,57.840000,iSTOXX Inv.Leveraged -1X MSFT I

In [4]:
# SHORT TERM STOCK PRICE
company.history(period="1d")  # intraday data

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price,Close,Dividends,High,Low,Open,Stock Splits,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,
2020-07-06,201.868652,0.0,202.280637,199.368048,200.077037,0.0,31897600
2020-07-07,199.521362,0.0,205.672271,199.272265,201.629148,0.0,33600700
2020-07-08,203.909378,0.0,204.321348,199.942904,201.265067,0.0,33600000
2020-07-09,205.336945,0.0,207.310599,202.606394,207.262692,0.0,33121700
2020-07-10,204.714172,0.0,205.106991,202.232734,204.666265,0.0,26177600
...,...,...,...,...,...,...,...
2025-06-27,495.940002,0.0,499.299988,493.029999,497.549988,0.0,34539200
2025-06-30,497.410004,0.0,500.760010,495.329987,497.040009,0.0,28369000
2025-07-01,492.049988,0.0,498.049988,490.980011,496.470001,0.0,19945400
2025-07-02,491.089996,0.0,493.500000,488.700012,489.989990,0.0,16310800
2025-07-03,498.839996,0.0,500.119995,493.440002,493.494995,0.0,13917734

In [7]:
#Long term stock price
company.history(period="5y")  # long-term performance

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-07-06 00:00:00-04:00,200.077037,202.280637,199.368048,201.868652,31897600,0.0,0.0
2020-07-07 00:00:00-04:00,201.629133,205.672255,199.272250,199.521347,33600700,0.0,0.0
2020-07-08 00:00:00-04:00,201.265052,204.321333,199.942889,203.909363,33600000,0.0,0.0
2020-07-09 00:00:00-04:00,207.262707,207.310614,202.606409,205.336960,33121700,0.0,0.0
2020-07-10 00:00:00-04:00,204.666250,205.106976,202.232719,204.714157,26177600,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-27 00:00:00-04:00,497.549988,499.299988,493.029999,495.940002,34539200,0.0,0.0
2025-06-30 00:00:00-04:00,497.040009,500.760010,495.329987,497.410004,28369000,0.0,0.0
2025-07-01 00:00:00-04:00,496.470001,498.049988,490.980011,492.049988,19945400,0.0,0.0
2025-07-02 00:00:00-04:00,489.989990,493.500000,488.700012,491.089996,16310800,0.0,0.0
2025-07-03 00:00:00-04:00,493.494995,500.119995,493.440002,498.839996,13917734,0.0,0.0

In [9]:
#ask price
info = company.info
bid = info['bid']
bid

469.2

In [10]:
#sell price
ask = info['ask']
ask

515.0

In [11]:
#spread
print(ask - bid)

45.80000000000001

In [12]:
# revenue and profitability ratios
company.financials #income statement

,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Tax Effect Of Unusual Items,-99918000.0,-2850000.0,43754000.0,180160797.164637
Tax Rate For Calcs,0.182,0.19,0.131,0.138266
Normalized EBITDA,133558000000.0,105155000000.0,99905000000.0,83831000000.0
Total Unusual Items,-549000000.0,-15000000.0,334000000.0,1303000000.0
Total Unusual Items Excluding Goodwill,-549000000.0,-15000000.0,334000000.0,1303000000.0
Net Income From Continuing Operation Net Minority Interest,88136000000.0,72361000000.0,72738000000.0,61271000000.0
Reconciled Depreciation,22287000000.0,13861000000.0,14460000000.0,11686000000.0
Reconciled Cost Of Revenue,74114000000.0,65863000000.0,62650000000.0,52232000000.0
EBITDA,133009000000.0,105140000000.0,100239000000.0,85134000000.0
EBIT,110722000000.0,91279000000.0,85779000000.0,73448000000.0
Net Interest Income,222000000.0,1026000000.0,31000000.0,-215000000.0
Interest Expense,2935000000.0,1968000000.0,2063000000.0,2346000000.0
Interest Income,3157000000.0,2994000000.0,2094000000.0,2131000000.0
Normalized Income,88585082000.0,72373150000.0,72447754000.0,60148160797.164635
Net Income From Continuing And Discontinued Operation,88136000000.0,72361000000.0,72738000000.0,61271000000.0
Total Expenses,135689000000.0,123392000000.0,114887000000.0,98172000000.0
Total Operating Income As Reported,109433000000.0,88523000000.0,83383000000.0,69916000000.0
Diluted Average Shares,7469000000.0,7472000000.0,7540000000.0,7608000000.0
Basic Average Shares,7431000000.0,7446000000.0,7496000000.0,7547000000.0
Diluted EPS,11.8,9.68,9.65,8.05
Basic EPS,11.86,9.72,9.7,8.12
Diluted NI Availto Com Stockholders,88136000000.0,72361000000.0,72738000000.0,61271000000.0
Net Income Common Stockholders,88136000000.0,72361000000.0,72738000000.0,61271000000.0
Net Income,88136000000.0,72361000000.0,72738000000.0,61271000000.0
Net Income Including Noncontrolling Interests,88136000000.0,72361000000.0,72738000000.0,61271000000.0
Net Income Continuous Operations,88136000000.0,72361000000.0,72738000000.0,61271000000.0
Tax Provision,19651000000.0,16950000000.0,10978000000.0,9831000000.0
Pretax Income,107787000000.0,89311000000.0,83716000000.0,71102000000.0
Other Income Expense,-1868000000.0,-238000000.0,302000000.0,1401000000.0
Other Non Operating Income Expenses,-1319000000.0,-223000000.0,-32000000.0,98000000.0
Special Income Charges,-206000000.0,-30000000.0,-101000000.0,-13000000.0
Write Off,206000000.0,30000000.0,101000000.0,13000000.0
Gain On Sale Of Security,-343000000.0,15000000.0,435000000.0,1316000000.0
Net Non Operating Interest Income Expense,222000000.0,1026000000.0,31000000.0,-215000000.0
Interest Expense Non Operating,2935000000.0,1968000000.0,2063000000.0,2346000000.0
Interest Income Non Operating,3157000000.0,2994000000.0,2094000000.0,2131000000.0
Operating Income,109433000000.0,88523000000.0,83383000000.0,69916000000.0
Operating Expense,61575000000.0,57529000000.0,52237000000.0,45940000000.0
Research And Development,29510000000.0,27195000000.0,24512000000.0,20716000000.0
Selling General And Administration,32065000000.0,30334000000.0,27725000000.0,25224000000.0
Selling And Marketing Expense,24456000000.0,22759000000.0,21825000000.0,20117000000.0
General And Administrative Expense,7609000000.0,7575000000.0,5900000000.0,5107000000.0
Other Gand A,7609000000.0,7575000000.0,5900000000.0,5107000000.0
Gross Profit,171008000000.0,146052000000.0,135620000000.0,115856000000.0
Cost Of Revenue,74114000000.0,65863000000.0,62650000000.0,52232000000.0
Total Revenue,245122000000.0,211915000000.0,198270000000.0,168088000000.0
Operating Revenue,245122000000.0,211915000000.0,198270000000.0,168088000000.0

In [13]:
company.balance_sheet

,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Ordinary Shares Number,7434138859.0,7432000000.0,7464000000.0,7519000000.0
Share Issued,7434138859.0,7432000000.0,7464000000.0,7519000000.0
Net Debt,33315000000.0,12533000000.0,35850000000.0,43922000000.0
Total Debt,67127000000.0,59965000000.0,61270000000.0,67775000000.0
Tangible Book Value,121660000000.0,128971000000.0,87720000000.0,84477000000.0
...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,75531000000.0,111256000000.0,104749000000.0,130256000000.0
Other Short Term Investments,57216000000.0,76552000000.0,90818000000.0,116032000000.0
Cash And Cash Equivalents,18315000000.0,34704000000.0,13931000000.0,14224000000.0
Cash Equivalents,6744000000.0,26226000000.0,5673000000.0,6952000000.0
Cash Financial,11571000000.0,8478000000.0,8258000000.0,7272000000.0

In [14]:
company.cashflow

,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Free Cash Flow,74071000000.0,59475000000.0,65149000000.0,56118000000.0
Repurchase Of Capital Stock,-17254000000.0,-22245000000.0,-32696000000.0,-27385000000.0
Repayment Of Debt,-29070000000.0,-2750000000.0,-9023000000.0,-3750000000.0
Issuance Of Debt,29645000000.0,0.0,0.0,NaN
Issuance Of Capital Stock,2002000000.0,1866000000.0,1841000000.0,1693000000.0
Capital Expenditure,-44477000000.0,-28107000000.0,-23886000000.0,-20622000000.0
End Cash Position,18315000000.0,34704000000.0,13931000000.0,14224000000.0
Beginning Cash Position,34704000000.0,13931000000.0,14224000000.0,13576000000.0
Effect Of Exchange Rate Changes,-210000000.0,-194000000.0,-141000000.0,-29000000.0
Changes In Cash,-16179000000.0,20967000000.0,-152000000.0,677000000.0
Financing Cash Flow,-37757000000.0,-43935000000.0,-58876000000.0,-48486000000.0
Cash Flow From Continuing Financing Activities,-37757000000.0,-43935000000.0,-58876000000.0,-48486000000.0
Net Other Financing Charges,-1309000000.0,-1006000000.0,-863000000.0,-2523000000.0
Cash Dividends Paid,-21771000000.0,-19800000000.0,-18135000000.0,-16521000000.0
Common Stock Dividend Paid,-21771000000.0,-19800000000.0,-18135000000.0,-16521000000.0
Net Common Stock Issuance,-15252000000.0,-20379000000.0,-30855000000.0,-25692000000.0
Common Stock Payments,-17254000000.0,-22245000000.0,-32696000000.0,-27385000000.0
Common Stock Issuance,2002000000.0,1866000000.0,1841000000.0,1693000000.0
Net Issuance Payments Of Debt,575000000.0,-2750000000.0,-9023000000.0,-3750000000.0
Net Short Term Debt Issuance,5250000000.0,0.0,0.0,NaN
Short Term Debt Issuance,5250000000.0,0.0,0.0,NaN
Net Long Term Debt Issuance,-4675000000.0,-2750000000.0,-9023000000.0,-3750000000.0
Long Term Debt Payments,-29070000000.0,-2750000000.0,-9023000000.0,-3750000000.0
Long Term Debt Issuance,24395000000.0,0.0,0.0,NaN
Investing Cash Flow,-96970000000.0,-22680000000.0,-30311000000.0,-27577000000.0
Cash Flow From Continuing Investing Activities,-96970000000.0,-22680000000.0,-30311000000.0,-27577000000.0
Net Other Investing Changes,-1298000000.0,-3116000000.0,-2825000000.0,-922000000.0
Net Investment Purchase And Sale,17937000000.0,10213000000.0,18438000000.0,2876000000.0
Sale Of Investment,35669000000.0,47864000000.0,44894000000.0,65800000000.0
Purchase Of Investment,-17732000000.0,-37651000000.0,-26456000000.0,-62924000000.0
Net Business Purchase And Sale,-69132000000.0,-1670000000.0,-22038000000.0,-8909000000.0
Purchase Of Business,-69132000000.0,-1670000000.0,-22038000000.0,-8909000000.0
Net PPE Purchase And Sale,-44477000000.0,-28107000000.0,-23886000000.0,-20622000000.0
Purchase Of PPE,-44477000000.0,-28107000000.0,-23886000000.0,-20622000000.0
Operating Cash Flow,118548000000.0,87582000000.0,89035000000.0,76740000000.0
Cash Flow From Continuing Operating Activities,118548000000.0,87582000000.0,89035000000.0,76740000000.0
Change In Working Capital,1824000000.0,-2388000000.0,446000000.0,-936000000.0
Change In Other Working Capital,5348000000.0,5535000000.0,5109000000.0,4633000000.0
Change In Other Current Liabilities,5616000000.0,2825000000.0,3169000000.0,5551000000.0
Change In Other Current Assets,-8465000000.0,-4824000000.0,-3514000000.0,-4391000000.0
Change In Payables And Accrued Expense,5232000000.0,-3079000000.0,3639000000.0,489000000.0
Change In Payable,5232000000.0,-3079000000.0,3639000000.0,489000000.0
Change In Account Payable,3545000000.0,-2721000000.0,2943000000.0,2798000000.0
Change In Tax Payable,1687000000.0,-358000000.0,696000000.0,-2309000000.0
Change In Income Tax Payable,1687000000.0,-358000000.0,696000000.0,-2309000000.0
Change In Inventory,1284000000.0,1242000000.0,-1123000000.0,-737000000.0
Change In Receivables,-7191000000.0,-4087000000.0,-6834000000.0,-6481000000.0
Changes In Account Receivables,-7191000000.0,-4087000000.0,-6834000000.0,-6481000000.0
Stock Based Compensation,10734000000.0,9611000000.0,7502000000.0,6118000000.0
Unrealized Gain Loss On Investment Securities,-146000000.0,-303000000.0,-509000000.0,-1057000000.0
Asset Impairment Charge,206000000.0,30000000.0,101000000.0,13000000.0
Deferred Tax,-4738000000.0,-6059000000.0,-5702000000.0,-150000000.0
Deferred Income Tax,-4738000000.0,-6059000000.0,-5702000000.0,-150000000.0
Depreciation Amortization Depletion,22287000000.0,13861000000.0,14460000000.0,11686000000.0
Depreciation And Amortization,22287000000.0,13861000000.0,14460000000.0,11686000000.0
Depreciation,22287000000.0,13861000000.0,14460000000.0,11686000000.0
Operating Gains Losses,245000000.0,469000000.0,-1000000.0,-205000000.0
Gain Loss On Investment Securities,245000000.0,469000000.0,-1000000.0,-205000000.0
Net Income From Continuing Operations,88136000000.0,72361000000.0,72738000000.0,61271000000.0

In [15]:
import yfinance as yf
import pandas as pd

def analyze_financials(company):
    ticker = yf.Ticker(company)

    # Get financial statements
    income = ticker.financials       # Income statement (columns = years)
    balance = ticker.balance_sheet   # Balance sheet
    cashflow = ticker.cashflow       # Cash flow statement

    # Transpose for easier access (rows = years)
    income = income.T
    balance = balance.T

    # Sort years descending (most recent first)
    income.sort_index(ascending=False, inplace=True)
    balance.sort_index(ascending=False, inplace=True)

    try:
        # Revenue Growth (Year-over-Year)
        revenue_growth = (income.loc[income.index[0], 'Total Revenue'] - income.loc[income.index[1], 'Total Revenue']) / income.loc[income.index[1], 'Total Revenue']

        # Profit Margin = Net Income / Total Revenue
        profit_margin = income.loc[income.index[0], 'Net Income'] / income.loc[income.index[0], 'Total Revenue']

        # Gross Margin = Gross Profit / Total Revenue
        gross_margin = income.loc[income.index[0], 'Gross Profit'] / income.loc[income.index[0], 'Total Revenue']

        # ROE = Net Income / Shareholder Equity
        net_income = income.loc[income.index[0], 'Net Income']
        total_equity = balance.loc[balance.index[0], "Total Stockholder Equity"]
        roe = net_income / total_equity

        print(f"📊 Financial Summary for {company}:")
        print(f"Revenue Growth (YoY): {revenue_growth:.2%}")
        print(f"Profit Margin:         {profit_margin:.2%}")
        print(f"Gross Margin:          {gross_margin:.2%}")
        print(f"Return on Equity (ROE):{roe:.2%}")

    except KeyError as e:
        print(f"Missing key in financials: {e}")
    except Exception as e:
        print(f"Error calculating financials: {e}")

# Example: Microsoft
analyze_financials(company)

AttributeError: 'Ticker' object has no attribute 'upper'

In [19]:
income = company.financials
print("Available items:", income.index)
print("Available periods:", income.columns)

Available items: Index(['Tax Effect Of Unusual Items', 'Tax Rate For Calcs',
       'Normalized EBITDA',
       'Net Income From Continuing Operation Net Minority Interest',
       'Reconciled Depreciation', 'Reconciled Cost Of Revenue', 'EBITDA',
       'EBIT', 'Net Interest Income', 'Interest Expense', 'Interest Income',
       'Normalized Income',
       'Net Income From Continuing And Discontinued Operation',
       'Total Expenses', 'Total Operating Income As Reported',
       'Diluted Average Shares', 'Basic Average Shares', 'Diluted EPS',
       'Basic EPS', 'Diluted NI Availto Com Stockholders',
       'Net Income Common Stockholders', 'Net Income',
       'Net Income Including Noncontrolling Interests',
       'Net Income Continuous Operations', 'Tax Provision', 'Pretax Income',
       'Other Income Expense', 'Other Non Operating Income Expenses',
       'Net Non Operating Interest Income Expense',
       'Interest Expense Non Operating', 'Interest Income Non Operating',
       'Operating Income', 'Operating Expense', 'Research And Development',
       'Selling General And Administration', 'Gross Profit', 'Cost Of Revenue',
       'Total Revenue', 'Operating Revenue'],
      dtype='object')
Available periods: DatetimeIndex(['2024-09-30', '2023-09-30', '2022-09-30', '2021-09-30',
               '2020-09-30'],
              dtype='datetime64[ns]', freq=None)